### PR TITLE
Reorganize the repo into sub-proposals

### PR DESCRIPTION
**Pull request by bvisness**
The repo has been organized into several sub-proposals, as well as updating the proposals to reflect the most recent discussion from CG meetings and other in-person meetings.

### CODE REVIEW

**Comment by dtig** [comment]
How do you feel about splitting these into separate PRs? I'm migrating over some of my comments from the docs, and I realize that there's maybe enough discussion to be had on the separate proposals where it would be confusing to follow  for anyone else without enough context. Concretely: 

 - Keep the overview document, but link other documents as needed from there - it's usually hard to find a starting point if an overview document doesn't exist.
 - Separate byob.md, virtual.md & static-protection.md into their own PRs

**Comment by bvisness** [comment]
Sure, that seems reasonable. I'll take care of that sometime today.

**Comment by bvisness** [comment]
Actually, after further thought, I think I'd rather just get these merged and then start separate issues for discussion of each proposal. Those issues can be linked from the sub-proposal documents for visibility. It makes more sense to me to have discussion _after_ each sub-proposal overview can be read by everyone, rather than in a PR that would introduce the overview in the first place. I'm reverting my prior changes.

**Comment by bvisness** [comment]
Overall the goal of _this_ PR was to reorganize the repo, not to be the home for discussion. If you have issues with the sub-proposal structure or the new Overview.md, or you have concrete issues with any of the sub-proposals (e.g. typos), please let me know. Otherwise, I think I'll merge this and kick off all the discussion issues.

**Comment by dtig** [comment]
We can merge this for now, but there's enough discussion to be had in each of those that maybe we should also kick off a discussion about scoping an MVP. I'm generally concerned that this is expanding the scope of the proposal but doesn't clearly document what is feasible and what isn't. Lgtm to merge, but also documenting high level feedback on all the approaches we've discussed before. 

- Streaming APIs may not support SABs in the sort/medium term, and the detach semantics are pretty baked into the APIs and, that's a compat risk and unlikely to change in the short/medium term. I'd be comfortable with investigating this as a post-MVP effort though.
- The `virtual` mode doesn't have a straightforward path to an implementation in a web engine, specifically would need to address how it could be accessed through JS/Web APIs
- static-protection is promising, but having a discussion about signal handling especially in the context of engines that would be interested in this proposal would a prerequisite. Speaking from the Chrome perspective, significant layout changes to memory would need to have stronger motivations than ergonomic improvements.

**Review by dtig — APPROVED** [review]

**Pull request merged**
